# The name of the stepm just as a reference.
name: "mdl and Python style checks"
description: "This check will run several scripts to ensure the formatting."
author: "hduff@esri.com"

inputs:
  FILE_PATHS:
    description: "Files to run the checks on."
    required: true

runs:
  using: "docker"
  image: "Dockerfile.dockerfile"
  args:
    - "--string"
    - ${{ inputs.FILE_PATHS }}